version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: go-redis-app
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
